name: HA Remote Installer
version: "1.0"
slug: ha_remote_installer
description: "Addon to install Wireguard-client and modify HA configuration"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: true  